server:
  port: 8901
logging:
  level:
    root: INFO

# spring config
spring:
  application:
    name: customer-service
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: messages

  # database postgresql
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/customer
    username: admin
    password: admin
    pool:
      initial-size: 50
      max-size: 100
      enabled: true
#      validation-query: select 1
#      max-life-time: 9223372036854775807

  # liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

# jwt token
jwt:
  token-expiration-seconds: 36000
  secret-key: e9b7826de98f5e8cb9108ac1db21a3a5b82a516b984a9efc10f32032d467e7d2
