kind: ConfigMap
apiVersion: v1
metadata:
  namespace: bu-order
  name: sme-search-service
data:
  application.yaml: |
    server:
      port: 8080
    client:
      elasticsearch:
        address: http://10.207.252.76:8703
        name: elasticsearchClient
      #define client here
    application:
      index:
        indexScores:
          - name: news
            score: 1
          - name: services
            score: 4
      whiteList:
        - uri: /actuator/health
          methods:
            - GET
        - uri: /**
          methods:
            - GET
            - POST
            - PUT
            - OPTIONS

