server:
  port: 7777
logging:
#  config: classpath:log4j2-dev.xml
  level:
    root: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
client:
  auth:
    internal-oauth: true
    address: http://localhost:8088/v1
    name: auth
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000
keycloak:
  clientId: ezbuy-client
  clientSecret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
  realm: ezbuy-server
  serverUrl: http://localhost:8080
  host: localhost
spring:
#  jmx:
#    enabled: false
#  devtools:
#    livereload:
#      enabled: true
#      port: 35729
  application:
    name: notification-service
  main:
#    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    basename: messages
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/notification
    username: admin
    password: admin
  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ezbuy-client
            client-secret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
            authorization-grant-type: password #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/certs
      keycloak:
        client-id: ezbuy-client
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangtien2k3qx1@gmail.com
    password: uvbskgpuchmgtlbp
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      ssl.enable: true
      tls.trust: smtp.gmail.com
      tls.enable: true
application:
  http-logging:
    request:
      enable: true
      header: true
      param: true
      body: true
    response:
      enable: true
      body: true
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
    - uri: /**
      methods:
        - OPTIONS
    - uri: /v1/transmission/create-noti
      methods:
        - POST
config:
  resendCount: 2
