app:
  config:
    keycloak:
      url: http://localhost:8080
      realm: ezbuy-server
logging:
  config: classpath:log4j2-dev.xml
spring:
  application:
    name: notification-service
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ezbuy-client
            client-secret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
            authorization-grant-type: password #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ezbuy-server/protocol/openid-connect/certs
      keycloak:
        client-id: web-client
  cloud:
    kubernetes:
      discovery:
        namespaces:
          - bu-order
      reload:
        enabled: false
      secrets:
        name: sme-noti-service
        namespace: bu-order
        sources:
          - name: sme-noti-service
      config:
        name: sme-noti-service
        namespace: bu-order
        sources:
          - name: sme-noti-service
management:
  endpoint:
    web:
      exposure:
        include: health, metrics, prometheus
    health:
      show-details: always
  health:
    redis:
      enabled: false
    elasticsearch:
      enabled: false
    mail:
      enabled: false
