version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0.3'
    executor: jdk
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:21.0.3'

orbs:
  maven: circleci/maven@1.4.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
          verify_dependencies: false
      - build:
          context: SonarCloud
