# server config
server:
  port: 8888
#logging
logging:
  pattern:
    console: "%d{dd/MM/yy HH:mm:ss}|%X{traceId}|%m%n"
  level:
    root: INFO

# spring config
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/notification
    username: admin
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangtien2k3qx1@gmail.com
    password: tjib jbht tlbp zwzo
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            authorization-grant-type: password #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/certs
      keycloak:
        client-id: ${keycloak.clientId}
#keycloak client config
keycloak:
  clientId: ezbuy-client
  clientSecret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
  realm: ezbuy-server
  serverUrl: http://localhost:8080
  host: localhost
client:
  auth:
    internal-oauth: true
    address: http://localhost/v1
    name: auth
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000

  sms-brandname:
    internal-oauth: true
    name: smsBrandNameClient
    address: https://hoangtien2k3.wiremockapi.cloud/api/v1
    username: usr
    password: 123456a@A
  order-cp:
    address: http://10.207.252.104:8074/services/order/PricingService?wsdl
    username: order
    password: order
    name: pricingClient
    timeout:
      read: 600000
      write: 600000
  setting:
    internal-oauth: true
    name: settingClient
    address: http://localhost:8081/v1
# unauthenticated endpoints config
application:
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
# config query
config:
  resendCount: 2
  limit: 800

#config send sms backDay
mode:
  send:
    backDay: 5

