server:
  port: 8090
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: INFO
---
#eureka-service config
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka
---
# Enable Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Apply CORS rules globally for all paths
            allowed-origin-patterns:
              - "http://localhost:*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      #http connect timeout
      #      httpclient:
      #        connect-timeout: 50000
      #        response-timeout: 10s
      discovery:
        locator:
          enabled: true #Allow self-routing via service name
          lower-case-service-id: true
