server:
  port: 8090
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: INFO
---
#health check
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

    gateway:
      globalcors:
        httpclient:
          connect-timeout: 50000
          response-timeout: 10s
        cors-configurations:
          '[/**]': # Apply CORS rules globally for all paths
            allowed-origin-patterns:
              - "http://localhost:*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # ============================
        # AUTH-SERVICE
        # ============================
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/v1/auth/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # CART-SERVICE
        # ============================
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/v1/cart/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # NOTI-SERVICE
        # ============================
        - id: NOTI-SERVICE
          uri: lb://NOTI-SERVICE
          predicates:
            - Path=/v1/noti/transmission/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # ORDER-SERVICE
        # ============================
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v1/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # PAYMENT-SERVICE
        # ============================
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/v1/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # PRODUCT-SERVICE
        # ============================
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # RATING-SERVICE
        # ============================
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/v1/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # SEARCH-SERVICE
        # ============================
        - id: SEARCH-SERVICE
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/v1/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # SETTING-SERVICE
        # ============================
        - id: SETTING-SERVICE
          uri: lb://SETTING-SERVICE
          predicates:
            - Path=/v1/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2

        # ============================
        # TRIGGER-SERVICE
        # ============================
        - id: TRIGGER-SERVICE
          uri: lb://TRIGGER-SERVICE
          predicates:
            - Path=/v1/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  first-backoff: 500ms
                  max-backoff: 2s
                  factor: 2