# application config
server:
  port: 8081
logging:
  level:
    root: INFO

# spring config
spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:mariadb://10.207.222.154:9001/sme_payment
    username: admin
    password: 123456@
  codec:
    max-in-memory-size: 10MB
#    mariadb:
#      url: r2dbc:mariadb://admin:123456@@10.207.222.154:9001/sme_payment
# web client config
client:
  product:
    address: http://10.207.252.223/sme-product
    name: product
  order:
    internal-oauth: true
    address: http://localhost:8082
    name: orderClient
  auth:
    internal-oauth: true
    address: http://10.207.252.223/sme-auth/v1
    name: authClient
  payment:
    address: http://10.207.252.223/mvt-api/myviettel.php/merchant
#    address: http://localhost:8088/sme-payment
    merchantCode: PORTAL_SME_CA
    accessCode: 54c08f1d6d0a9a797247ffe5df85799a817acd363e6d2ee1fd1ebeb341f09c39
    hashCode: e0476743357d9e62ce711dbebb52f2f8fc48085af2e5083805a74ad05a529c4c
    templateCheckoutLink: http://10.58.71.186:8080/checkout?merchant_code={0}&check_sum={1}&order_code={2}&trans_amount={3}&cancel_url={4}&return_url={5}&is_combo={6}
    templateCheckoutComboLink: http://10.58.71.186:8080/checkout?merchant_code={0}&check_sum={1}&order_code={2}&trans_amount={3}&cancel_url={4}&return_url={5}&is_combo={6}&hub_combo={7}
    algorithm: HmacSHA1
    name: paymentClient
  setting:
    address: http://10.207.252.223/sme-setting/
    name: settingClient
# unauthenticated endpoints config
application:
  http-logging:
    request:
      enable: true
      header: true
      param: true
      body: true
    response:
      enable: true
      body: true
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
    - uri: /price/calculate
      methods:
        - POST
    - uri: /v1/payment/create-link-checkout
      methods:
        - POST
    - uri: /v1/payment/payment-result
      methods:
        - POST
    - uri: /v1/payment/sync-payment
      methods:
        - POST
  data:
    sync-payment:
      limit: 500
