server:
  port: 8092
oauth2:
  keycloak:
    client-uri: http://localhost:36355/auth/realms/sme-portal/protocol/openid-connect/token
    client-id: web-client
    client-secret: jzLlmUxlxLMMOpnjkNU3wMDZuCKB8GUE
client:
  product:
    address: http://localhost:8090/product/v1/product
    name: product
    pool:
      max-size: 100
      max-pending-acquire: 100
  order:
    address: http://10.207.252.104:8918/services/order/OrderSmePortalService
    username: order
    password: order@#123
    name: orderClient
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000
management:
  endpoint:
    health:
      show-details: never
  health:
    elasticsearch:
      enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    mariadb:
      url: r2dbc:mariadb://admin:123456%40@10.207.222.154:9001/sme_order
      pool:
        initial-size: 50
        max-size: 100
        enabled: true
        validation-query: select 1
        max-life-time: 9223372036854775807
application:
  white-list:
    - uri: /v1/order/**
      methods:
        - GET
