# server config
server:
  port: 8082
# ot=oauth
#keycloak:
#  clientId: web-client
#  clientSecret: 24bcf1ec-4746-4cf6-9939-b56e6ca394b3
#  realm: sme-portal
#  serverUrl: http://sme-keycloak.bu-order.svc:8080/auth
#oauth2:
#  keycloak:
#    client-uri: http://192.168.26.57:18080/auth/realms/sme-portal
#    client-id: web-client
#    client-secret: 24bcf1ec-4746-4cf6-9939-b56e6ca394b3
# spring config
spring:
  codec:
    max-in-memory-size: 10MB
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:mariadb://10.207.222.154:9001/sme_order
    username: admin
    password: 123456@
# web client config
client:
  product:
    internal-oauth: true
#    address: http://localhost:8088/
    address: http://10.207.252.223/sme-product/
    name: productClient
  setting:
    internal-oauth: true
    address: http://10.207.252.223/sme-setting/
    name: settingClient
  payment:
    internal-oauth: true
#    address: http://10.207.252.223/sme-payment/
    address: http://localhost:8081/
    name: paymentClient
  cart:
    internal-oauth: true
    address: http://10.207.252.223/sme-cart/
    name: cartClient
  gateway:
    internal-oauth: true
    address: http://10.207.252.223/sme-gateway/
    name: gatewayClient
  order:
    address: http://10.207.252.104:8918/services/order/OrderSmePortalService
    username: order
    password: order@#123
    name: orderClient
    systemStaffCode: PORTAL_SME
    staffRevenue: PORTAL_SME
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 30000
      write: 10000
  profile:
    address: http://10.58.71.240:8565/wsap?wsdl
    username: profile_bccs
    password: profile_bccs
    name: profileClient
  pricing:
    address: http://10.207.252.104:8099/services/pricing/PricingService
    username: order
    password: order
    name: pricingClient
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000
  cm:
    address: http://10.58.71.238:8701/SALE_SERVICE/bpm/sale/externalSystem/InterfaceSaleMBCCS
    username: sale
    password: sale
    name: cmClient
  cmPortal:
    address: http://10.58.71.238:8701/SALE_SERVICE/bpm/sale/externalSystem/InterfaceSalePortalSme?wsdl
    username: sale
    password: sale
    name: cmPortalClient
    timeout:
      read: 100000
      write: 100000
  order-v2:
    internal-oauth: true
    address: http://10.207.252.75:8068/services/order/SmePortalService?wsdl
    name: orderV2Client
    username: order
    password: order
    timeout:
      read: 600000
      write: 1000
  auth:
    internal-oauth: true
#    address: http://localhost:8089/v1
    address: http://10.207.252.223/sme-auth/v1
    name: authClient
  organization:
    internal-oauth: true
    address: http://localhost:8089/v1
    name: organizationClient
  pro:
    host: 10.58.34.5
    port: 8065
    username: cm_owner
    password: cm_owner
    async: true
# unauthenticated endpoints config
application:
  http-logging:
    request:
      enable: true
      header: true
      param: true
      body: true
    response:
      enable: true
      body: true
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
    - uri: /**
      methods:
        - GET
        - POST
    - uri: /v1/order/**
      methods:
        - GET
        - POST
        - OPTIONS
    - uri: /v1/order/ca/add-group-member
    - uri: /v1/order/ca/remove-group-member
    - uri: /v1/order/ca/update-group-member
    - uri: /v1/order/ca/get-number-sign

  data:
    sync-order:
      limit: 500
    system-user: HANTT #user tao don hang
  connectCA:
    returnUrl: http://10.207.252.223:8787/connect-ca-result/
    cancelUrl: http://10.207.252.223:8787/payment-result-fail
  connectOrder:
    returnUrl: http://10.207.252.223:8787/connect-order-result/
    cancelUrl: http://10.207.252.223:8787/payment-result-fail
