# server config
server:
  port: 8932
#logging
logging:
  pattern:
    console: "%d{dd/MM/yy HH:mm:ss}|%X{traceId}|%m%n"
  level:
    root: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

# spring config
spring:
  application:
    name: order-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    basename: messages

  r2dbc:
    url: r2dbc:postgresql://localhost:5434/order
    username: admin
    password: admin

  #security oauth2
  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            authorization-grant-type: ${keycloak.grantType} #password || #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/certs
      keycloak:
        client-id: ${keycloak.clientId}

#keycloak client config
keycloak:
  clientId: ezbuy-client
  clientSecret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
  realm: ezbuy-server
  serverUrl: http://localhost:8080
  grantType: password
  host: localhost

# web client config
client:
  product:
    internal-oauth: true
    token-relay: true
    address: http://localhost:8056/
    name: productClient
  product-v2:
    internal-oauth: true
    address: http://localhost:8081/
    name: productClientV2
  setting:
    internal-oauth: true
    address: http://locahost:8081/
    name: settingClient
  payment:
    internal-oauth: true
    address: http://localhost:8081/
    name: paymentClient
  cart:
    internal-oauth: true
    address: http://localhost:8056/
    name: cartClient
  auth:
    internal-oauth: true
    address: http://localhost:8089/v1
    name: authClient
# unauthenticated endpoints config
application:
  http-logging:
    request:
      enable: true
      header: true
      param: true
      body: true
    response:
      enable: true
      body: true
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
    - uri: /**
      methods:
        - GET
        - POST
    - uri: /v1/order/**
      methods:
        - GET
        - POST
        - OPTIONS
    - uri: /v1/order/ca/add-group-member
    - uri: /v1/order/ca/remove-group-member
    - uri: /v1/order/ca/update-group-member
    - uri: /v1/order/ca/get-number-sign

  data:
    sync-order:
      limit: 500
    system-user: hoangtien2k3 #user tao don hang
  connectCA:
    returnUrl: http://localhost:8787/connect-ca-result/
    cancelUrl: http://localhost:8787/payment-result-fail
  connectOrder:
    returnUrl: http://localhost:8787/connect-order-result/
    cancelUrl: http://localhost:8787/payment-result-fail
