server:
  port: 8088
logging:
  level:
    root: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
client:
  #define client here
  setting:
    internal-oauth: true
    address: http://10.207.252.223/sme-setting/v1
    name: settingClient
    pool:
      max-size: 100
      max-pending-acquire: 100
  auth:
    internal-oauth: true
    address: http://10.207.252.223/sme-auth/v1/
    name: authClient
  order:
    internal-oauth: true
    address: http://10.207.252.223/sme-order/v1/
    name: orderClient
    pool:
      max-size: 100
      max-pending-acquire: 100
  sync:
    internal-oauth: true
    address: http://10.207.252.223/sme-sync/v1/
    name: syncClient
  product:
    address: http://10.207.252.145:8801/PRODUCT_SERVICE/bpm/product/InterfaceProductService
    username: product
    password: product
    staffCode: HANN
    name: productClient
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000
  cm:
    address: http://10.207.252.105:9083/SALE_SERVICE/bpm/sale/externalSystem/InterfaceSalePortalSme
    username: sale
    password: sale
    name: cmClient
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000
  ca:
    address: http://10.58.71.166:8333/WS_CA/SDKPayment/CaServiceForSmePortal #rest api
    username: 1ad0e3d776c05dbce60bfa1b98cd0143
    password: 8964f27dfccd0ecd82dd17dd969a0adf
    name: caClient
spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:mariadb://10.207.222.154:9001/sme_product
    username: admin
    password: 123456@
application:
  http-logging:
    request:
      enable: true
      header: true
      param: true
      body: true
    response:
      enable: true
      body: true
  whiteList:
    - uri: /v1/**
      methods:
        - POST
        - GET
        - OPTIONS
    - uri: /actuator/health
      methods:
        - GET
    - uri: /v1/filter-product-template
      methods:
        - POST
    - uri: /v1/filter-template
      methods:
        - GET
        - POST
        - PUT
        - OPTIONS
    - uri: /v1/sync-subscriber-order
      methods:
        - POST
    - uri: /v1/telecom-service/**
    - uri: /v1/service-group/**
    - uri: /v1/telecom-service-related
    - uri: /v1/telecom-service-connect
    - uri: /v1/telecom-service-related/**
    - uri: /v1/subscriber-by-id-no/**
    - uri: /v1/mega-menu
      methods:
        - GET
    - uri: /v1/get-list-product-offering-combo-v2
      methods:
        - POST
# white list api
#    - uri: /v1/service-group/group-and-service-active
#      methods:
#        - GET
time:
  sync:
    subscriber: 30
