# server config
server:
  port: 8888
#logging
logging:
  pattern:
    console: "%d{dd/MM/yy HH:mm:ss}|%X{traceId}|%m%n"
  level:
    root: INFO

# spring config
spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:9001/sme_ezbuy
    username: admin
    password: admin

  mail:
    host: smtp.viettel.com.vn
    port: 465
    username: username@viettel.com.vn
    password: password
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.viettel.com.vn
      ssl.enable: true
      tls.trust: smtp.viettel.com.vn
      tls.enable: true

  mail-first:
    host: smtp.viettel.com.vn
    port: 465
    username: username@viettel.com.vn
    password: password

  mail-second:
    host: smtp.viettel.com.vn
    port: 465
    username: username@viettel.com.vn
    password: password

  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            authorization-grant-type: password #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/certs
      keycloak:
        client-id: ${keycloak.clientId}
#keycloak client config
keycloak:
  clientId: ezbuy-client
  clientSecret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
  realm: ezbuy-server
  serverUrl: http://localhost:8080
  host: localhost
client:
  sms-brandname:
    internal-oauth: true
    name: smsBrandNameClient
    address: https://apismsbrandname.viettelai.vn:8000/api/v1
    username: usr
    password: 123456a@A

  allow:
    send:
      sms: true
  test:
    number: 0828007853
  mode:
    send:
      sms: 2
      backDay: 5

  setting:
    internal-oauth: true
    name: settingClient
    address: http://localhost:8081/v1

  auth:
    internal-oauth: true
    address: http://localhost:8089/v1
    name: auth
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000

# unauthenticated endpoints config
application:
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
# config query
config:
  resendCount: 2
  limit: 800

adtech:
  date-inactive: 14