cd ../api-gateway-service/deployment/sandbox && ./deploy.sh
cd ../auth-service/deployment/sandbox && ./deploy.sh
cd ../cart-service/deployment/sandbox && ./deploy.sh
cd ../customer-service/deployment/sandbox && ./deploy.sh
cd ../noti-service/deployment/sandbox && ./deploy.sh
cd ../order-service/deployment/sandbox && ./deploy.sh
cd ../payment-service/deployment/sandbox && ./deploy.sh
cd ../product-service/deployment/sandbox && ./deploy.sh
cd ../rating-service/deployment/sandbox && ./deploy.sh
cd ../search-service/deployment/sandbox && ./deploy.sh
cd ../send-notification-service/deployment/sandbox && ./deploy.sh
cd ../setting-service/deployment/sandbox && ./deploy.sh
cd ../sync-service/deployment/sandbox && ./deploy.sh
cd ../trigger-service/deployment/sandbox && ./deploy.sh
