cd ../ezbuy-auth/deployment && ./deploy.sh
cd ../ezbuy-cart/deployment && ./deploy.sh
cd ../ezbuy-gateway/deployment && ./deploy.sh
cd ../ezbuy-noti/deployment && ./deploy.sh
cd ../ezbuy-order/deployment && ./deploy.sh
cd ../ezbuy-payment/deployment && ./deploy.sh
cd ../ezbuy-product/deployment && ./deploy.sh
cd ../ezbuy-rating/deployment && ./deploy.sh
cd ../ezbuy-search/deployment && ./deploy.sh
cd ../ezbuy-setting/deployment && ./deploy.sh
cd ../ezbuy-trigger/deployment && ./deploy.sh
