server:
  port: 8080
client:
  product:
    address: http://10.207.252.223/sme-product/
    name: product
    pool:
      max-size: 100
      max-pending-acquire: 100
  setting:
    address: http://10.207.252.223/sme-setting/v1
    name: setting
    pool:
      max-size: 100
      max-pending-acquire: 100
  payment:
    internal-oauth: true
    address: http://10.207.252.223/sme-payment/v1
    name: payment
    pool:
      max-size: 100
      max-pending-acquire: 100
spring:
  security:
    oauth2:
      keycloak:
        client-id: web-client
        client-secret: 24bcf1ec-4746-4cf6-9939-b56e6ca394b3
  r2dbc:
    mariadb:
      url: r2dbc:mariadb://admin:123456%40@10.207.222.154:9001/sme_cart
application:
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
    - uri: /**
      methods:
        - GET
        - POST
        - PUT
        - DELETE
