# server config
server:
  port: 8888
#logging
logging:
  pattern:
    console: "%d{dd/MM/yy HH:mm:ss}|%X{traceId}|%m%n"
  level:
    root: INFO

# spring config
spring:
  application:
    name: notification-send
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://postgres:5434/notification
    username: admin
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangtien2k3qx1@gmail.com
    password: tjib jbht tlbp zwzo
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true

  #security oauth2
  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            authorization-grant-type: password #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/certs
      keycloak:
        client-id: ${keycloak.clientId}

#keycloak client config
keycloak:
  clientId: ezbuy-client
  clientSecret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
  realm: ezbuy-server
  serverUrl: http://keycloak:8080
  host: localhost

client:
  auth:
    internal-oauth: true
    address: http://ezbuy-auth-service:8089/v1
    name: auth
    pool:
      max-size: 100
      max-pending-acquire: 100
    timeout:
      read: 60000
      write: 1000
# unauthenticated endpoints config
application:
  whiteList:
    - uri: /actuator/health
      methods:
        - GET
# config query
config:
  resendCount: 2
  limit: 800

#scheduled send mail
scheduled:
  fixedRate: 30000
  initialDelay: 5000

#eureka-service config
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always