name: Auto Merge Develop into Master

on:
  push:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Git
        run: |
          git config --global user.email "hoangtien2k3qx1@gmail.com"
          git config --global user.name "hoangtien2k3"

      - name: Pull latest changes from master
        run: |
          git pull origin master

      - name: Merge develop into master
        run: |
          git fetch origin develop
          git merge origin/develop

      - name: Push merged changes to master
        run: |
          git push origin master

      - name: Notify merge success
        run: |
          echo "Merge from develop to master completed successfully"
