name: payment-service service ci

on:
  push:
    branches: [ "master" ]
    paths:
      - "payment-service/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/payment-service-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "payment-service/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/payment-service-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests -f payment-service
      - name: Run Maven Test
        run: mvn test -f payment-service
      - name: Unit Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: Unit-Test-Results
          path: "payment-service/**/surefire-reports/*.xml"
          reporter: java-junit
      - name: Analyze with sonar cloud
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f payment-service
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./payment-service
          push: true
          tags: ghcr.io/hoangtien2k3/ezbuy-payment-service:latest
